[package]
name = "interest-form-api"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = "1.5.16"
lambda_http = "0.13.0"
once_cell = "1.19.0"
tokio = { version = "1", features = ["macros"] }

