version: "3.8"

services:
  dynamodb:
    image: amazon/dynamodb-local:2.5.4
    container_name: dynamodb
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./dynamodb_data:/var/lib/dynamodb'
    environment:
      - AWS_REGION=us-west-1
